spring:
  application:
    name: console-api

server:
  port: 8080

grpc:
  client:
    contract-manager:
      address: static://contract-manager:9091
      negotiationType: PLAINTEXT
    customer-manager:
      address: static://customer-manager:9092
      negotiationType: PLAINTEXT
    pricing-manager:
      address: static://pricing-manager:9093
      negotiationType: PLAINTEXT
