# Configurazione principale per console-api
spring:
  application:
    name: console-api
    version: 0.0.1-SNAPSHOT

  # Configurazione MongoDB
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://localhost:27017/console

server:
  port: 8080

# Configurazione gRPC client
grpc:
  client:
    contract-manager:
      address: localhost:9091
      negotiation-type: plaintext
    customer-manager:
      address: localhost:9092
      negotiation-type: plaintext
    pricing-manager:
      address: localhost:9093
      negotiation-type: plaintext

# Logging
logging:
  level:
    root: INFO
    it.salspa: DEBUG

