spring:
  application:
    name: contract-manager

grpc:
  server:
    port: 9091
  client:
    customer-manager:
      address: static://customer-manager:9092
      negotiationType: PLAINTEXT
    pricing-manager:
      address: static://pricing-manager:9093
      negotiationType: PLAINTEXT
