# Configurazione principale per contract-manager-core
spring:
  application:
    name: contract-manager-core
    version: 0.0.1-SNAPSHOT

  # Configurazione MongoDB
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://localhost:27018/contract?retryWrites=false

# Configurazione gRPC server
grpc:
  server:
    port: 9091
    enable-keep-alive: true
    max-inbound-message-size: 4194304

  # Client per comunicare con altri servizi
  client:
    customer-manager:
      address: localhost:9092
      negotiation-type: plaintext

    pricing-manager:
      address: localhost:9093
      negotiation-type: plaintext

# Logging
logging:
  level:
    root: INFO
    it.salspa: DEBUG

