# Configurazione TEST per customer-manager-core
# Attivato con profilo 'test' insieme a 'docker'

spring:
  data:
    mongodb:
      uri: mongodb://mongodb-customer-test:27017/customer?replicaSet=rs-customer

grpc:
  client:
    contract-manager-service:
      address: contract-manager-core-test:9091
      negotiation-type: plaintext
    pricing-manager-service:
      address: pricing-manager-core-test:9093
      negotiation-type: plaintext
