# Configurazione principale per customer-manager-core
spring:
  application:
    name: customer-manager-core
    version: 0.0.1-SNAPSHOT

  # Configurazione MongoDB
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://localhost:27019/customer?retryWrites=false

# Configurazione gRPC server
grpc:
  server:
    port: 9092
    enable-keep-alive: true
    max-inbound-message-size: 4194304

  # Client per comunicare con altri servizi
  client:
    contract-manager-service:
      address: localhost:9091
      negotiation-type: plaintext

    pricing-manager-service:
      address: localhost:9093
      negotiation-type: plaintext

# Logging
logging:
  level:
    root: INFO
    it.salspa: DEBUG

